# Generated by Django 2.0.4 on 2018-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
