# Generated by Django 2.0.4 on 2018-04-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
            preserve_default=False,
        ),
    ]
